### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by GO1984** [eryk918/postgis_toolbox#2]
Unfortunatelly i can't connect:
PostgreSQL version 13.12 with PostGIS 3.4.0
![Screenshot_1](https://github.com/eryk918/postgis_toolbox/assets/20504033/9c9cd608-c443-45ee-b6cd-916fc517d2b4)

**Comment by eryk918** [comment]
Hi, you need to specify the port to connect to the database (default is 5432). In the next version of the tool, I will protect the connection creation dialog and add messages to warn against such errors.

**Comment by GO1984** [comment]
Thank you for the fast reply.
I use a service configured in a _.pg_service.conf_ service file on Win 11
so i cant add an additional service port.
do you think the next version will cover this issue too?

**Comment by GO1984** [comment]
I can see already the databases in the drop-down list but cant connect when clicking on the _connect_ button

**Comment by NyakudyaA** [comment]
Hi @eryk918 Please fix the issue as it is a blocker to using the tool, otherwise I will have to flag it as unapproved in the plugin list

**Comment by GO1984** [comment]
> You probably need to fill in the following fields with correct authentication data. ![image](https://user-images.githubusercontent.com/68321722/268602786-462d6ec0-8803-45f7-97dd-65c44ce559a5.png)

This doesn't fix it.

**Comment by NyakudyaA** [comment]
![Peek 2023-09-19 16-23](https://github.com/eryk918/postgis_toolbox/assets/2510900/1c0e97f7-2ba6-4d45-8903-7a2a537db56a)

This doesn't work

**Comment by eryk918** [comment]
> ![Peek 2023-09-19 16-23](https://user-images.githubusercontent.com/2510900/268989576-1c0e97f7-2ba6-4d45-8903-7a2a537db56a.gif) [ ![Peek 2023-09-19 16-23](https://user-images.githubusercontent.com/2510900/268989576-1c0e97f7-2ba6-4d45-8903-7a2a537db56a.gif) ](https://user-images.githubusercontent.com/2510900/268989576-1c0e97f7-2ba6-4d45-8903-7a2a537db56a.gif) [ ](https://user-images.githubusercontent.com/2510900/268989576-1c0e97f7-2ba6-4d45-8903-7a2a537db56a.gif)
> 
> This doesn't work

Thanks for the test scenario, I will analyze the situation in a moment and make a fix.

**Comment by eryk918** [comment]
I made a correction to the PostgreSQL connection management dialog - so that it does not throw python errors, I also added error logging for establishing a connection - they will be displayed in the Log messages panel. Thanks to this, we will find out what errors the database client returns to us and we will be able to solve them. Several people tested this plugin and none received this specific error. I've uploaded this patch to the QGIS Repository and am waiting for approve. When it is available, download the update and send us the logs, we will solve this problem. 😄 
Link to manual update file: https://github.com/eryk918/postgis_toolbox/releases/download/v1.1/postgis_toolbox.zip

**Comment by GO1984** [comment]
Thank you for your fast action.

With version 1.10 i now can connect to the databases, by credentials in details.
What still do not work, is the connection to the already in QGIS connected databases (wich connected by Postgresql services (here by .pg_service.conf). Information you can find here: [](https://www.postgresql.org/docs/current/libpq-pgservice.html) There is still an error message:

![Screenshot_1](https://github.com/eryk918/postgis_toolbox/assets/20504033/bf0678f7-810b-4db4-954d-b71a8fd6420d)

Maybe you want to fix this too?

**Comment by NyakudyaA** [comment]
The issue is that in the code https://github.com/eryk918/postgis_toolbox/blob/main/utils.py#L469-L486 there is no logic to handle service files logic.

**Comment by eryk918** [comment]
> Thank you for your fast action.
> 
> With version 1.10 i now can connect to the databases, by credentials in details.
> What still do not work, is the connection to the already in QGIS connected databases (wich connected by Postgresql services (here by .pg_service.conf). Information about the connection file you can find here: 
> [https://www.postgresql.org/docs/current/libpq-pgservice.html] There is still an error message:
> 
> ![Screenshot_1](https://github.com/eryk918/postgis_toolbox/assets/20504033/bf0678f7-810b-4db4-954d-b71a8fd6420d)
> 
> Maybe you want to fix this too?


To prevent this python error from being thrown, you need to edit and save old connections via Database Manager in PostGIS Toolbox.  After yesterday's fixes, this action should automatically fix old - bad connections.

**Comment by NyakudyaA** [comment]
On Ubuntu, this is caused by missing driver QPSQL. I saw the following error
`Qt: QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QSPATIALITE QTDS QTDS7`
And I resolved it by running `sudo apt install libqt5sql5-psql`
